version: '3.8'

services:
  api:
    build: .
    container_name: fraud_api
    ports:
      - "8000:8000"
    environment:
      - API_PORT=8000
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    restart: unless-stopped

  dashboard:
    build: .
    container_name: fraud_dashboard
    ports:
      - "8050:8050"
    command: python src/dashboard/monitoring_app.py
    volumes:
      - ./reports:/app/reports
    restart: unless-stopped
    depends_on:
      - api