data:
  raw: data/raw/data.csv
  processed: data/processed/clean.csv

model:
  type: RandomForestClassifier
  n_estimators: 100
  max_depth: 5
  random_state: 42

train:
  test_size: 0.2
  shuffle: true
