data:
  raw: data/raw/data.csv
  clean: data/processed/clean.csv
  features: data/processed/features.csv
  test_split: data/processed/test.npz

train:
  target: churn
  test_size: 0.2
  random_state: 42
  model_path: models/model.pkl
  penalty: l2
  C: 1.0
  max_iter: 1000
